// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWuurWbjLOkSw9X8aYAWWLPyphrSkbSNs',
    appId: '1:948018252249:web:3ecbf06c1218ec456871c8',
    messagingSenderId: '948018252249',
    projectId: 'wesikafinance',
    authDomain: 'wesikafinance.firebaseapp.com',
    storageBucket: 'wesikafinance.appspot.com',
    measurementId: 'G-RBGS5CRX0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpUyTM4GaxCYa_ZmVJt6llrbxhXC-AEXU',
    appId: '1:948018252249:android:ad375170bccb67d16871c8',
    messagingSenderId: '948018252249',
    projectId: 'wesikafinance',
    storageBucket: 'wesikafinance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbjv3UdQHGixTqHqCRGvKRyrp1c5TrLg',
    appId: '1:948018252249:ios:d8c42e11a800b7636871c8',
    messagingSenderId: '948018252249',
    projectId: 'wesikafinance',
    storageBucket: 'wesikafinance.appspot.com',
    androidClientId: '948018252249-bn52to95cf7fnifpabf9ri8lbidcqsn8.apps.googleusercontent.com',
    iosClientId: '948018252249-vrvuh2erli93i6mk423ee8pb0rlqg9l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wesika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYbjv3UdQHGixTqHqCRGvKRyrp1c5TrLg',
    appId: '1:948018252249:ios:164e99332c24b26a6871c8',
    messagingSenderId: '948018252249',
    projectId: 'wesikafinance',
    storageBucket: 'wesikafinance.appspot.com',
    androidClientId: '948018252249-bn52to95cf7fnifpabf9ri8lbidcqsn8.apps.googleusercontent.com',
    iosClientId: '948018252249-13832p5mu2rreitaod1dj6g5q7vepipm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wesika.RunnerTests',
  );
}
